#https://www.tpisoftware.com/tpu/articleDetails/1826
version: "3.7"

services:

  flask:
    build: .
    container_name: template_flask
    # restart: always
    environment:
      - APP_NAME=FlaskApp
    ports:
      - 9899:9899
    depends_on:
      - db
    entrypoint: /sample/dbsetup.sh

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    #資料持久化與本機共享資料夾
    volumes:
      - ./sqldata:/docker-entrypoint-initdb.d