#https://www.tpisoftware.com/tpu/articleDetails/1826
version: "3.7"

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_server
    command: gunicorn -b :9899 --threads 4 app:app --preload
    environment:
      - APP_NAME=FlaskApp
    expose:
      - 9899
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./nginx/log:/var/log/nginx

    depends_on:
      - flask